researcher:
  description: >
    Extract the information fields from the job offer input in markdown format:
    - Salary or salary range amount: if specified.
    - Required technologies: languages, frameworks, libraries, etc. separated by commas.
    - Optional technologies: languages, frameworks, libraries, etc. separated by commas.
    
    For each field, if no information is found in Markdown, just return an empty string.
    
    Job offer:

    {markdown}
  expected_output: >
    Just a valid json object.
    The json output must have the following fields and structure:
    {{
      "salary": "",
      "required_technologies": "",
      "optional_technologies": ""
    }}
  agent: researcher_agent
  verbose: true
