export const MOCK_JOB_1 = {
    id: 1,
    title: 'Frontend Engineer',
    company: 'Tech Corp',
    salary: '120k',
    location: 'Remote',
    url: 'http://example.com/1',
    markdown: 'Job Description',
    web_page: 'LinkedIn',
    created: '2023-01-01',
    modified: null,
    flagged: false,
    like: false,
    ignored: false,
    seen: false,
    applied: false,
    discarded: false,
    closed: false,
    ai_enriched: true,
    required_technologies: 'React',
    optional_technologies: 'TypeScript',
    client: null,
    comments: null,
    cv_match_percentage: 95,
};

export const MOCK_JOB_2 = {
    id: 2,
    title: 'Backend Developer',
    company: 'Data Inc',
    salary: '130k',
    location: 'New York',
    url: 'http://example.com/2',
    markdown: 'Backend Description',
    web_page: 'Indeed',
    created: '2023-01-02',
    modified: null,
    flagged: false,
    like: false,
    ignored: false,
    seen: false,
    applied: false,
    discarded: false,
    closed: false,
    ai_enriched: true,
    required_technologies: 'Python',
    optional_technologies: 'FastAPI',
    client: null,
    comments: null,
    cv_match_percentage: 88,
};

export const MOCK_JOBS_LIST = {
    items: [MOCK_JOB_1, MOCK_JOB_2],
    total: 2,
    page: 1,
    size: 20,
};

export const MOCK_SEARCH_BACKEND = {
    items: [MOCK_JOB_2],
    total: 1,
    page: 1,
    size: 20,
};
