# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Install commonlib dependencies
      run: cd packages/commonlib && poetry lock && poetry install --no-interaction && cd ../..
    - name: Install scrapper dependencies
      run: cd apps/scrapper && poetry lock && poetry install --no-interaction && cd ../..
    - name: Install viewer dependencies
      run: cd apps/viewer && poetry lock && poetry install --no-interaction && cd ../..
    - name: Install aiEnrich dependencies
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        cd apps/aiEnrich
        uv tool update-shell
        uv tool install crewai
        crewai install
        cd ../..
    - name: Run commonlib tests
      run: |
        cp '.env.example' .env
        cd packages/commonlib && poetry run pytest && cd ../..
    - name: Run scrapper tests
      run: cd apps/scrapper && poetry run pytest && cd ../..
    - name: Run viewer tests
      run: cd apps/viewer && poetry run pytest && cd ../..
    - name: Run aiEnrich tests
      run: cd apps/aiEnrich && uv run pytest && cd ../..
    # - name: Set PYTHONPATH
    #   run: echo "PYTHONPATH=src" >> $GITHUB_ENV
    # - name: Clean up __pycache__ and .pyc files
    #   run: |
    #     find . -type d -name "__pycache__" -exec rm -r {} +
    #     find . -type f -name "*.pyc" -exec rm -f {} +
    # - name: Lint with flake8
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: commonlib coverage
      run: |
        cd packages/commonlib
        poetry run coverage run -m pytest
        poetry run coverage report -m
        cd ../..
    - name: scrapper coverage
      run: |
        cd apps/scrapper
        poetry run coverage run -m pytest
        poetry run coverage report -m
        cd ../..
    - name: viewer coverage
      run: |
        cd apps/viewer
        poetry run coverage run -m pytest
        poetry run coverage report -m
        cd ../..
    - name: aiEnrich coverage
      run: |
        cd apps/aiEnrich
        uv run coverage run -m pytest
        uv run coverage report -m
        cd ../..        
    # - name: Coverage badge
    #   run: |
    #     coverage-badge -o coverage.svg -f
